version: '3'
services:
  discovery-service:
    image: finder/discovery-service
    build:
      dockerfile: ./Dockerfile
      context: ../../discovery-service
    ports:
      - "8761:8761"
  gateway:
    image: finder/gateway
    build:
      dockerfile: ./Dockerfile
      context: ../../gateway
    ports:
      - "5555:5555"
      - "8001:8001"
    links:
      - "discovery-service:discovery-service"
    environment:
      SERVER_PORT: "5555"
      DEBUG_PORT: "8001"
      DISCOVERY_URI: "http://discovery-service:8761/eureka/"
  auth-server:
    image: finder/auth-server
    build:
      dockerfile: ./Dockerfile
      context: ../../auth-server
    ports:
      - "8901:8901"
      - "8002:8002"
    links:
      - "gateway:gateway"
      - "discovery-service:discovery-service"
      - "finder-postgres:finder-postgres"
    environment:
      SERVER_PORT: "8901"
      DEBUG_PORT: "8002"
      KAFKASERVER_URI: "kafkaserver:9092"
      DISCOVERY_URI: "http://discovery-service:8761/eureka/"
      DB_URI: "jdbc:postgresql://finder-postgres:5432/finder"
    depends_on:
      - finder-postgres
      - kafkaserver
  finder-postgres:
    image: postgres:9.6
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: finder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - finder-postgres-volume:/var/lib/postgresql/data
  mail-server:
    image: finder/mail-server
    build:
      dockerfile: ./Dockerfile
      context: ../../mail-server
    ports:
      - "8025:8025"
      - "8003:8003"
    links:
      - "discovery-service:discovery-service"
    environment:
      SERVER_PORT: "8025"
      DEBUG_PORT: "8003"
      KAFKASERVER_URI: "kafkaserver:9092"
      DISCOVERY_URI: "http://discovery-service:8761/eureka/"
    depends_on:
      - kafkaserver
  file-storage:
    image: finder/file-storage
    build:
      dockerfile: ./Dockerfile
      context: ../../file-storage
    ports:
      - "8180:8180"
      - "8004:8004"
    links:
      - "discovery-service:discovery-service"
    environment:
      SERVER_PORT: "8180"
      DEBUG_PORT: "8004"
      DISCOVERY_URI: "http://discovery-service:8761/eureka/"
  finder-service:
    image: finder/finder-service
    build:
      dockerfile: ./Dockerfile
      context: ../../finder-service
    ports:
      - "9080:9080"
      - "8005:8005"
    links:
      - "gateway:gateway"
      - "discovery-service:discovery-service"
      - "finder-postgres:finder-postgres"
    environment:
      SERVER_PORT: "9080"
      DEBUG_PORT: "8005"
      DISCOVERY_URI: "http://discovery-service:8761/eureka/"
      DB_URI: "jdbc:postgresql://finder-postgres:5432/finder"
    depends_on:
      - finder-postgres
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181
  kafkaserver:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaserver:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  finder-postgres-volume:
    external: true