spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finder
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    stream:
      bindings:
        output:
          destination: userTopic
          content-type: application/json
#  kafka:
#    bootstrap-servers: kafkaserver:9092


jwt:
  token:
    secret: JWTeDiToRaPp
    refresh:
      expired: 32400000
    bearer:
      expired: 32400000

swagger:
  enabled: true

app:
    mailServerEnabled: true
    hostUrl: http://localhost:5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/