server:
  port: 5555

  #Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.testmicoservice: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
#  prefix:  /api
  routes:
    auth-server: /api/auth/**
    finder-service: /api/finder/**
  sensitive-headers: Authorization
  ignoredHeaders: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
