swagger:
  enabled: true

spring:
  servlet:
    multipart:
      max-file-size:  2MB
      max-request-size: 2MB

#amazon
amazon:
  bucket:
    accessKey: AKIAJPVSTGIRRREJGTFA
    secretKey: 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
    region: eu-central-1
    name: finder-app-test
    url: https://finder-app-test.s3.eu-central-1.amazonaws.com


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/