spring:
  mail:
    host: smtp.gmail.com
    username: foodTinder2020@gmail.com
    password: finder2demo
    port: 587
    protocol: smtp

mail:
  starttls:
    enable: true
  from: foodTinder2020@gmail.com
  auth: true
  debug: true
  activationCodeUrl: http://18.156.122.205

swagger:
  enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/